import { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import About from '../components/About'
import ContactMe from '../components/ContactMe'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import WorkExperience from '../components/WorkExperience'
import { Experience, PageInfo, Project, Skill, Social } from '../typings'
import { fetchExperiences } from '../utils/fetchExperiences'
import { fetchPageInfo } from '../utils/fetchPageInfo'
import { fetchProject } from '../utils/fetchProjects'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchSocial } from '../utils/fetchSocials'

type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
}

export default function Home({pageInfo, experiences, skills, projects, socials}:Props) {
  return (
    <div className='scrollbar bg-[rgb(36,36,36)] text-white h-screen overflow-scroll snap-y snap-mandatory z-0 overflow-y-scroll overflow-x-hidden scroll-smooth'>
      <Head>
        <title>Santiago Aguirre Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header socials={socials}/>
      {/* Hero */}

        <section  id="hero" className='snap-center'>
          <Hero pageInfo={pageInfo}/>
        </section>

      {/* About */}

      <section id="about" className='snap-center'>
        <About pageInfo={pageInfo}/>
      </section>

      {/* Experience */}
      <section id='experience' className='snap-center'>
        <WorkExperience experiences={experiences}/>
      </section>

      {/* Skills */}

      <section id='skills' className='snap-start'>
        <Skills skills={skills}/>
      </section>

      {/* Projects */}

      <section id='projects' className='snap-start'>
        <Projects projects={projects}/>
      </section>

      {/* Contact me */}

      <section id='contact' className='snap-start'>
        <ContactMe/>
      </section>

      <Footer/>

    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const experiences: Experience[] = await fetchExperiences();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProject();
  const socials: Social[] = await fetchSocial()

  return {
    props : {
      pageInfo,
      experiences,
      skills,
      projects,
      socials,
    },
    revalidate: 10000,
  }
}
