import Head from 'next/head'
import About from '../components/About'
import ContactMe from '../components/ContactMe'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import WorkExperience from '../components/WorkExperience'

export default function Home() {
  return (
    <div className='scrollbar bg-[rgb(36,36,36)] text-white h-screen overflow-scroll snap-y snap-mandatory z-0 overflow-y-scroll overflow-x-hidden scroll-smooth'>
      <Head>
        <title>Santiago Aguirre Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      {/* Hero */}

        <section  id="hero" className='snap-center'>
          <Hero/>
        </section>

      {/* About */}

      <section id="about" className='snap-center'>
        <About/>
      </section>

      {/* Experience */}
      <section id='experience' className='snap-center'>
        <WorkExperience/>
      </section>

      {/* Skills */}

      <section id='skills' className='snap-start'>
        <Skills/>
      </section>

      {/* Projects */}

      <section id='projects' className='snap-start'>
        <Projects/>
      </section>

      {/* Contact me */}

      <section id='contact' className='snap-start'>
        <ContactMe/>
      </section>

    </div>
  )
}
